In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from itertools import product
plt.style.use("seaborn-v0_8")

In [2]:
prices_raw_0 = pd.read_csv("prices_round_3_day_0.csv", sep = ";", index_col = "timestamp")
prices_raw_1 = pd.read_csv("prices_round_4_day_1.csv", sep = ";", index_col = "timestamp")
prices_raw_2 = pd.read_csv("prices_round_4_day_2.csv", sep = ";", index_col = "timestamp")
prices_raw_3 = pd.read_csv("prices_round_4_day_3.csv", sep = ";", index_col = "timestamp")

In [3]:
prices_raw_1.index = prices_raw_1.index + prices_raw_0.index.max() + 100
prices_raw_2.index = prices_raw_2.index + prices_raw_1.index.max() + 100
prices_raw_3.index = prices_raw_3.index + prices_raw_2.index.max() + 100
prices_raw = pd.concat([prices_raw_0, prices_raw_1, prices_raw_2, prices_raw_3], axis=0)
prices_raw

,day,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
timestamp,,,,,,,,,,,,,,,,
0,0,VEV_5400,22,25,NaN,NaN,NaN,NaN,24,25,NaN,NaN,NaN,NaN,23.0,0.0
0,0,VEV_6500,0,16,NaN,NaN,NaN,NaN,1,16,NaN,NaN,NaN,NaN,0.5,0.0
0,0,VEV_5500,8,25,NaN,NaN,NaN,NaN,9,25,NaN,NaN,NaN,NaN,8.5,0.0
0,0,VEV_5200,100,19,NaN,NaN,NaN,NaN,103,6,104.0,13.0,NaN,NaN,101.5,0.0
0,0,VEV_5300,52,6,51.0,19.0,NaN,NaN,54,25,NaN,NaN,NaN,NaN,53.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3999900,3,VEV_5100,140,6,139.0,21.0,NaN,NaN,143,6,144.0,21.0,NaN,NaN,141.5,0.0
3999900,3,VEV_5200,69,6,68.0,21.0,NaN,NaN,71,27,NaN,NaN,NaN,NaN,70.0,0.0
3999900,3,VEV_5000,231,27,NaN,NaN,NaN,NaN,237,27,NaN,NaN,NaN,NaN,234.0,0.0
3999900,3,VEV_6000,0,24,NaN,NaN,NaN,NaN,1,24,NaN,NaN,NaN,NaN,0.5,0.0
3999900,3,VELVETFRUIT_EXTRACT,5229,61,NaN,NaN,NaN,NaN,5235,61,NaN,NaN,NaN,NaN,5232.0,0.0

In [4]:
vev = prices_raw[prices_raw["product"] == "VEV_6000"]
vev

,day,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
timestamp,,,,,,,,,,,,,,,,
0,0,VEV_6000,0,25,NaN,NaN,NaN,NaN,1,25,NaN,NaN,NaN,NaN,0.5,0.0
100,0,VEV_6000,0,17,NaN,NaN,NaN,NaN,1,17,NaN,NaN,NaN,NaN,0.5,0.0
200,0,VEV_6000,0,24,NaN,NaN,NaN,NaN,1,24,NaN,NaN,NaN,NaN,0.5,0.0
300,0,VEV_6000,0,20,NaN,NaN,NaN,NaN,1,20,NaN,NaN,NaN,NaN,0.5,0.0
400,0,VEV_6000,0,19,NaN,NaN,NaN,NaN,1,19,NaN,NaN,NaN,NaN,0.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3999500,3,VEV_6000,0,22,NaN,NaN,NaN,NaN,1,22,NaN,NaN,NaN,NaN,0.5,0.0
3999600,3,VEV_6000,0,18,NaN,NaN,NaN,NaN,1,18,NaN,NaN,NaN,NaN,0.5,0.0
3999700,3,VEV_6000,0,26,NaN,NaN,NaN,NaN,1,26,NaN,NaN,NaN,NaN,0.5,0.0
3999800,3,VEV_6000,0,20,NaN,NaN,NaN,NaN,1,20,NaN,NaN,NaN,NaN,0.5,0.0
3999900,3,VEV_6000,0,24,NaN,NaN,NaN,NaN,1,24,NaN,NaN,NaN,NaN,0.5,0.0

In [8]:
products = [
  "HYDROGEL_PACK",
  "VELVETFRUIT_EXTRACT",
  "VEV_4000",
  "VEV_4500",
  "VEV_5000",
  "VEV_5100",
  "VEV_5200",
  "VEV_5300",
  "VEV_5400",
  "VEV_5500",
  "VEV_6000",
  "VEV_6500"
]

In [9]:
for p in products:
  prices = prices_raw[prices_raw["product"] == p]
  print(f"-----{p}------")
  print("mean: ", prices["mid_price"].mean())
  print("std: ", prices["mid_price"].std())

-----HYDROGEL_PACK------
mean:  9993.73125
std:  32.58828333685041
-----VELVETFRUIT_EXTRACT------
mean:  5247.3641
std:  17.090768957235134
-----VEV_4000------
mean:  1247.3734375
std:  17.11391131017711
-----VEV_4500------
mean:  747.3729625
std:  17.104593517578255
-----VEV_5000------
mean:  251.6733125
std:  16.381335880552594
-----VEV_5100------
mean:  162.6744
std:  15.326695903885419
-----VEV_5200------
mean:  91.1128375
std:  12.796427437471563
-----VEV_5300------
mean:  43.10535
std:  8.97591655790384
-----VEV_5400------
mean:  14.08915
std:  4.608139065950911
-----VEV_5500------
mean:  5.545575
std:  2.4769969332281416
-----VEV_6000------
mean:  0.5
std:  0.0
-----VEV_6500------
mean:  0.5
std:  0.0

1.738849034284364